mysql:
  url: jdbc:mysql://172.16.65.7:3306/demo?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
  username: root
  password: 002526

eureka:
  instance: localhost
  port: 8011
